baseURL = "https://mirianbr.com"
languageCode = "en-us"
title = "Mírian Bruckschen Motta Barros's Website"
theme = "hello-friend-ng"
paginate = 10

[author]
  name = "Mírian Bruckschen Motta Barros"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  title = "Mírian Bruckschen Motta Barros"
  
  # Subtitle for home
  homeSubtitle = "Consulting services on technical documentation, customer service and supporting business processes.  Contact me at hello@mirianbr.com 👋🏼"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Mírian Bruckschen Motta Barros"
  keywords = "technical writing, technical documentation, it consulting, technical writing consulting"
  images = [""]

  copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'


[taxonomies]
    tag = "tags"

[params.footer]
    trademark = true
    rss = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a> and <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">Hello Friend NG</a> theme"
    ]

[[params.social]]
  name = "email"
  url = "mailto:hello@mirianbr.com"
[[params.social]]
  name = "github"
  url = "https://github.com/mirianbr"
[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/mirianbruckschen/"
[[params.social]]
  name = "kaggle"
  url = "https://www.kaggle.com/mirianbarros"
[[params.social]]
  name = "itchio"
  url = "https://mirianbr.itch.io/"

defaultContentLang = 'en'
[languages]
  [languages.en]
    subtitle = "Technical Documentation and Customer Services Consultant"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "homepage"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name       = "About"
        url        = "/about"
        weight     = 1
      [[languages.en.menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts"
        weight     = 2
      [[languages.en.menu.main]]
        identifier = "projects"
        name       = "Projects"
        url        = "/projects"
        weight     = 3
      [[languages.en.menu.main]]
        identifier = "ptbr"
        name       = "🇧🇷"
        url        = "/pt"
        weight     = 4
      
  
  [languages.pt]
    contentDir = "content/pt"
    
    subtitle = "Consultoria em Documentação Técnica e Atendimento ao Cliente"
    homeSubtitle = "Consultoria em documentação técnica, atendimento ao cliente e processos de negócio de apoio. Contato: hello@mirianbr.com 👋🏼"

    keywords = "consultoria em ti, documentação técnica, escrita técnica"
    readOtherPosts = "Leia mais"

    [languages.pt.params.logo]
      logoText = "início"
      logoHomeLink = "/pt"

    [languages.pt.menu]
      [[languages.pt.menu.main]]
        identifier = "about-pt"
        name       = "Sobre"
        url        = "/pt/sobre"
        weight     = 1
      [[languages.pt.menu.main]]
        identifier = "blog-pt"
        name       = "Blog"
        url        = "/pt/posts"
        weight     = 2
      [[languages.pt.menu.main]]
        identifier = "projects-pt"
        name       = "Projetos"
        url        = "/pt/projetos"
        weight     = 3
      [[languages.pt.menu.main]]
        identifier = "english"
        name       = "🇺🇸"
        url        = "../"
        weight     = 4